version: "3.8"
services:
  db:
    container_name: greenlight_db
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=greenlight
    ports:
      - "5432:5432"
    volumes:
      - greenlight_db:/var/lib/postgresql/data

volumes:
  greenlight_db:
